name: flutter_application_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.18.0
  responsive_sizer: ^3.3.1
  font_awesome_flutter: ^10.8.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2 # 추가된 부분

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png" # 아이콘으로 사용할 이미지 경로 설정
